# Generated by Django 3.1.1 on 2020-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(to='polling_app.Survey'),
        ),
    ]
