# Generated by Django 3.1.1 on 2020-10-29 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0004_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroptions',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='related_question',
            field=models.ManyToManyField(through='polling_app.SurveyQuestion', to='polling_app.Question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_no', to='polling_app.survey'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerOptions',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
