# Generated by Django 3.1.1 on 2020-10-29 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0005_auto_20201029_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('key_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('diverse', 'Diverse')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('interview_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polling_app.respondent')),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='related_question',
        ),
        migrations.AddField(
            model_name='survey',
            name='related_question',
            field=models.ManyToManyField(to='polling_app.Question'),
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.survey'),
        ),
        migrations.AddField(
            model_name='answeroptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.answeroptions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.response'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polling_app.category'),
        ),
    ]
