# Generated by Django 3.1.1 on 2020-10-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0006_auto_20201029_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('key_name', models.CharField(default=None, max_length=200)),
                ('value', models.CharField(default=None, max_length=200)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.question')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.answeroption'),
        ),
        migrations.DeleteModel(
            name='AnswerOptions',
        ),
    ]
