# Generated by Django 3.1.1 on 2020-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0007_auto_20201030_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories of Questions'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Set of answers to surveys', 'verbose_name_plural': 'Sets of answers to surveys'},
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='key_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('single_choice', 'Single Choice'), ('date', 'Date'), ('multiple_choice', 'Multiple Choice'), ('stated_preference', 'Stated Preference')], default=models.CharField(max_length=500), max_length=200),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='location',
            field=models.CharField(choices=[('germany', 'Germany'), ('austria', 'Austria'), ('switzerland', 'Switzerland'), ('france', 'France')], max_length=50),
        ),
    ]
