# Generated by Django 3.1.1 on 2020-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0008_auto_20201106_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'questions', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['name'], 'verbose_name': 'survey', 'verbose_name_plural': 'surveys'},
        ),
        migrations.AlterField(
            model_name='survey',
            name='expiryDate',
            field=models.DateField(verbose_name='expiry date'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='publishDate',
            field=models.DateField(verbose_name='publication date'),
        ),
    ]
