# Generated by Django 3.1.1 on 2020-12-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0009_auto_20201129_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories of Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_app.question', verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('single_choice', 'Single Choice'), ('date', 'Date'), ('multiple_choice', 'Multiple Choice'), ('stated_preference', 'Stated Preference')], default=models.TextField(verbose_name='Text'), max_length=200),
        ),
    ]
