# Generated by Django 2.2.14 on 2020-12-30 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0010_auto_20201201_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['text'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerOptions', to='polling_app.Question', verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='expiryDate',
            field=models.DateField(default=datetime.date(2021, 1, 9), verbose_name='expiry date'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='survey',
            name='publishDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='publication date'),
        ),
    ]
