# Generated by Django 2.2.14 on 2020-12-30 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0011_auto_20201230_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='expiryDate',
            field=models.DateField(default=datetime.date(2021, 1, 10), verbose_name='expiry date'),
        ),
    ]
